version: "3.8"
services:
  backend:
    image: "bibhasha/springboot-react-fullstack:22.4.2022.0.39.21"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
